[package]
name = "tiny-db-exp"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1.0", default-features = false, features = [ "derive"]}
bincode = "1.3"

[dev-dependencies]
tempfile = "3.10.1"
